include $(THEOS)/makefiles/common.mk

TWEAK_NAME = mrybootstrap
mrybootstrap_FILES = Tweak.xm
mrybootstrap_CFLAGS = -fobjc-arc -I../Include
ADDITIONAL_CFLAGS = -DTHEOS_LEAN_AND_MEAN

include $(THEOS_MAKE_PATH)/tweak.mk
