INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = 00mryipcSB
00mryipcSB_FILES = SBTweak.xm
00mryipcSB_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
