include $(THEOS)/makefiles/common.mk

TOOL_NAME = mryldrestart
mryldrestart_FILES = main.m
mryldrestart_CFLAGS = -fobjc-arc
mryldrestart_CODESIGN_FLAGS = -Sent.xml

include $(THEOS_MAKE_PATH)/tool.mk
